if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'CLAIMSRATE'
'CUSTOMERAGE'
'CUSTOMERMONETARYVALUE'
'EDUCATIONALDEGREE'
'FIRSTPOLICYYEAR'
'GEOGRAPHICLIVING'
'GROSSMONTHLYSALARY'
'HASCHILDREN'
'PREMIUMSINLOBHEALTH'
'PREMIUMSINLOBHOUSEHOLD'
'PREMIUMSINLOBLIFE'
'PREMIUMSINLOBMOTOR'
'PREMIUMSINLOBWORKCOMP'
) then ROLE='INPUT';
else delete;
end;
