retain _segFlag_ 0;
drop _segFlag_;
if upcase(name) = '_SEGMENT_' then do;
_segFlag_ = 1;
role = 'SEGMENT';
level = 'NOMINAL';
label = 'Segment Variable';
end;
else if upcase(name) = '_SEGMENT_LABEL_' then do;
role = 'REJECTED';
level = 'NOMINAL';
label = 'Segment Description';
end;
else if upcase(NAME) = 'DISTANCE' then do;
role = 'REJECTED';
level = 'INTERVAL';
end;
else if upcase(NAME) = '_IMPUTE_' then do;
role = 'REJECTED';
level = 'INTERVAL';
end;
output;
if ^_segFlag_ and _eof_ then do;
type = 'N';
index = 'N';
indexType = 'NONE';
format = '';
informat = '';
name = '_SEGMENT_';
role = 'SEGMENT';
level = 'NOMINAL';
label = 'Segment Variable';
output;
name = '_SEGMENT_LABEL_';
role = 'REJECTED';
level = 'NOMINAL';
label = 'Segment Description';
output;
name = 'Distance';
role = 'REJECTED';
level = 'INTERVAL';
label = 'Distance to Cluster Seed';
output;
name = '_Impute_';
role = 'REJECTED';
level = 'INTERVAL';
label = '';
output;
end;
