*;
*MOST FREQUENT VALUE (COUNT);
*;
length IMP_EducationalDegree $15;
format IMP_EducationalDegree $CHAR15.0;
label IMP_EducationalDegree = 'Imputed EducationalDegree';
IMP_EducationalDegree = EducationalDegree;
if EducationalDegree = '' then IMP_EducationalDegree = '3 - BSc/MSc';
format IMP_GeographicLiving BEST12.0;
label IMP_GeographicLiving = 'Imputed GeographicLiving';
IMP_GeographicLiving = GeographicLiving;
if GeographicLiving = . then IMP_GeographicLiving = 4;
format IMP_HasChildren BEST12.0;
label IMP_HasChildren = 'Imputed HasChildren';
IMP_HasChildren = HasChildren;
if HasChildren = . then IMP_HasChildren = 1;
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
format IMP_GrossMonthlySalary F12.0;
label IMP_GrossMonthlySalary = 'Imputed GrossMonthlySalary';
IMP_GrossMonthlySalary = GrossMonthlySalary;
if GrossMonthlySalary = . then IMP_GrossMonthlySalary = 5012.8385565;
format IMP_PremiumsinLOBHealth F12.2;
label IMP_PremiumsinLOBHealth = 'Imputed PremiumsinLOBHealth';
IMP_PremiumsinLOBHealth = PremiumsinLOBHealth;
if PremiumsinLOBHealth = . then IMP_PremiumsinLOBHealth = 171.58083293;
format IMP_PremiumsinLOBLife F12.2;
label IMP_PremiumsinLOBLife = 'Imputed PremiumsinLOBLife';
IMP_PremiumsinLOBLife = PremiumsinLOBLife;
if PremiumsinLOBLife = . then IMP_PremiumsinLOBLife = 41.855781986;
format IMP_PremiumsinLOBMotor F12.2;
label IMP_PremiumsinLOBMotor = 'Imputed PremiumsinLOBMotor';
IMP_PremiumsinLOBMotor = PremiumsinLOBMotor;
if PremiumsinLOBMotor = . then IMP_PremiumsinLOBMotor = 300.47025239;
format IMP_PremiumsinLOBWorkComp F12.2;
label IMP_PremiumsinLOBWorkComp = 'Imputed PremiumsinLOBWorkComp';
IMP_PremiumsinLOBWorkComp = PremiumsinLOBWorkComp;
if PremiumsinLOBWorkComp = . then IMP_PremiumsinLOBWorkComp = 41.277514202;
label IMP_REP_CustomerAge = 'Imputed: Replacement: CustomerAge';
IMP_REP_CustomerAge = REP_CustomerAge;
if REP_CustomerAge = . then IMP_REP_CustomerAge = 47.900758903;
label IMP_REP_FirstPolicyYear = 'Imputed: Replacement: FirstPolicyYear';
IMP_REP_FirstPolicyYear = REP_FirstPolicyYear;
if REP_FirstPolicyYear = . then IMP_REP_FirstPolicyYear = 1986.0170482;
