select(UPCASE(NAME));
when('SEGMENT') do;
ROLE = "&EM_PROPERTY_SEGMENTROLE"; LEVEL = "NOMINAL";
end;
when('SOM_SEGMENT') do;
ROLE = "&EM_PROPERTY_SEGMENTROLE"; LEVEL = "NOMINAL";
end;
when('SOM_DIMENSION1') do;
ROLE = 'INPUT'; LEVEL = 'NOMINAL';
end;
when('SOM_DIMENSION2') do;
ROLE = 'INPUT'; LEVEL = 'NOMINAL';
end;
when('DISTANCE') do;
ROLE = 'REJECTED'; LEVEL = 'INTERVAL';
end;
when('_IMPUTE_') do;
ROLE = 'REJECTED'; LEVEL = 'INTERVAL';
end;
when('SOM_ID') delete;
otherwise;
end;
